site_name: Kinescalade - Gérer les blessures en escalade
site_url: kinescalade.info

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences